services:
  - type: web
    name: crop-recommendation-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
